In [1]:
# Import necessary packages
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score
from sklearn.metrics import classification_report, confusion_matrix

# Neural Networks
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

In [2]:
pwd()

'/Users/aodubela'

In [3]:
cd Desktop/ExerciseFiles/Data

/Users/aodubela/Desktop/ExerciseFiles/Data


In [4]:
df = pd.read_csv('zoo.data.csv', header = 0)

In [5]:
df.columns=['Name','hair','feathers','eggs','milk','airborne','aquatic', 'predator', 'toothed','backbone','breathes','venomous','fins','legs','tail','domestic','catsize','type']

In [6]:
# Print the first few rows
df.head()

Name  hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0  antelope     1         0     0     1         0        0         0        1   
1      bass     0         0     1     0         0        1         1        1   
2      bear     1         0     0     1         0        0         1        1   
3      boar     1         0     0     1         0        0         1        1   
4   buffalo     1         0     0     1         0        0         0        1   

   backbone  breathes  venomous  fins  legs  tail  domestic  catsize  type  
0         1         1         0     0     4     1         0        1     1  
1         1         0         0     1     0     1         0        0     4  
2         1         1         0     0     4     0         0        1     1  
3         1         1         0     0     4     1         0        1     1  
4         1         1         0     0     4     1         0        1     1

In [7]:
print(df.shape)
df.describe()

(100, 18)


hair    feathers        eggs        milk    airborne     aquatic  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.420000    0.200000    0.590000    0.400000    0.240000    0.360000   
std      0.496045    0.402015    0.494311    0.492366    0.429235    0.482418   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    1.000000    0.000000    0.000000    0.000000   
75%      1.000000    0.000000    1.000000    1.000000    0.000000    1.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

       predator     toothed    backbone   breathes   venomous        fins  \
count    100.00  100.000000  100.000000  100.00000  100.00000  100.000000   
mean       0.55    0.600000    0.820000    0.79000    0.08000    0.170000   
std        0.50    0.492366    0.386123    0.40936    0.27266    0.377525   
min        0.00    0.000000    0.000000    0.00000    0.00000    0.000000   
25%        0.00    0.000000    1.000000    1.00000    0.00000    0.000000   
50%        1.00    1.000000    1.000000    1.00000    0.00000    0.000000   
75%        1.00    1.000000    1.000000    1.00000    0.00000    0.000000   
max        1.00    1.000000    1.000000    1.00000    1.00000    1.000000   

             legs        tail    domestic    catsize        type  
count  100.000000  100.000000  100.000000  100.00000  100.000000  
mean     2.830000    0.750000    0.130000    0.43000    2.850000  
std      2.040276    0.435194    0.337998    0.49757    2.105188  
min      0.000000    0.000000    0.000000    0.00000    1.000000  
25%      2.000000    0.750000    0.000000    0.00000    1.000000  
50%      3.000000    1.000000    0.000000    0.00000    2.000000  
75%      4.000000    1.000000    0.000000    1.00000    4.000000  
max      8.000000    1.000000    1.000000    1.00000    7.000000

In [8]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [9]:
# One hot encode labels
from sklearn.preprocessing import OneHotEncoder 

encoded_X = OneHotEncoder().fit_transform(X).toarray()
print(encoded_X)

[[1. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [10]:
# Split into Training & Testing Sets
X_train, X_test, y_train, y_test = train_test_split(encoded_X, y, test_size=0.30, random_state=123)

In [11]:
# Print feature data 
print(X_train.shape)
print(X_test.shape)

(70, 135)
(30, 135)


In [12]:
# Create Clasifier Object

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=250)

In [13]:
# Fit Classifier
mlp.fit(X_train, y_train)

/Users/aodubela/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(8, 8, 8), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=250,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [14]:
# Make Predictions

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [15]:
# Print metrics
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[29  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0]
 [ 0  0  4  0  0  0  0]
 [ 0  0  0  9  0  0  0]
 [ 1  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  9]]
              precision    recall  f1-score   support

           1       0.97      1.00      0.98        29
           2       1.00      1.00      1.00        14
           3       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         9
           5       1.00      0.50      0.67         2
           6       0.00      0.00      0.00         3
           7       0.75      1.00      0.86         9

    accuracy                           0.94        70
   macro avg       0.82      0.79      0.79        70
weighted avg       0.91      0.94      0.92        70



/Users/aodubela/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
